ISSUE_KEYWORDS = {
    "dent":               ["dent", "dented", "ding", "denting", "dents", "deformation", "depression", "hail dent", "dab gaya", "door dented", "is dented", "corner dent"],
    "scratch":            ["scratch", "scratched", "scuff", "scrape", "scraped", "mark", "abrasion", "scrape lag"],
    "crack":              ["crack", "cracked", "cracking", "hairline", "fracture", "crack line", "cracked screen", "pantalla cracked", "you crack", "screen crack", "body crack", "lid crack", "laptop crack", "taillight crack", "is cracked", "screen cracked", "lid is cracked", "crack on"],
    "glass_shatter":      ["shatter", "shattered", "shattering", "broken glass", "glass smashed", "spiderweb", "impact point"],
    "stain":              ["stain", "stained", "discoloration", "spill", "spilled", "marking", "ink", "oily mark", "oil stain", "dark mark", "liquid stain", "marks on the display"],
    "water_damage":       ["water", "water damage", "wet", "damp", "moisture", "moist", "liquid", "liquid damage", "flood", "wet box", "water damaged"],
    "torn_packaging":     ["torn", "tear", "ripped", "ripped open", "opened", "split", "torn package", "seal torn", "torn-open", "phati hui", "khola gaya", "torn seal", "seal damaged"],
    "crushed_packaging":  ["crush", "crushed", "squashed", "smashed", "compressed", "crumpled", "dented box", "corner crushed", "crush ho gaya", "crushed box", "box crushed", "package corner crushed"],
    "broken_part":        ["broken", "snapped", "detached", "separated", "cracked part", "shattered part", "fell off", "toot gaya", "hinge broke", "broken hai", "mirror broken", "dano", "danado", "damage", "damaged", "is damaged", "looks damaged", "got damaged"],
    "missing_part":       ["missing", "absent", "not present", "gone", "nowhere", "lost", "stolen", "not there", "keycaps came off", "faltan", "is missing", "are missing"],
    "none":               ["no damage", "none", "intact", "undamaged", "fine", "okay", "nothing wrong", "looks fine"],
}

PART_KEYWORDS = {
    "car": {
        "front_bumper":   ["front bumper", "bumper front", "front", "front side", "blue car front bumper"],
        "rear_bumper":    ["rear bumper", "back bumper", "rear", "parachoques trasero", "atras"],
        "door":           ["door", "doors", "door panel", "left side door", "side door"],
        "hood":           ["hood", "bonnet", "engine cover", "hail dents"],
        "windshield":     ["windshield", "windscreen", "front glass", "front screen", "front glass shatter"],
        "side_mirror":    ["mirror", "side mirror", "wing mirror", "rearview", "left mirror", "left side mirror"],
        "headlight":      ["headlight", "headlamp", "light front", "left headlight", "broken headlight"],
        "taillight":      ["taillight", "tail light", "rear light", "brake light", "back light"],
        "fender":         ["fender", "wheel arch", "mudguard"],
        "quarter_panel":  ["quarter panel", "rear quarter", "c pillar"],
        "body":           ["body", "body panel", "side panel", "car body", "car body panel"],
    },
    "laptop": {
        "screen":         ["screen", "display", "lcd", "monitor", "led", "pantalla", "display area"],
        "keyboard":       ["keyboard", "key", "keys", "keypad", "teclas", "keycaps"],
        "trackpad":       ["trackpad", "touchpad", "track pad", "mouse", "cursor", "palm-rest"],
        "hinge":          ["hinge", "pivot", "joint", "hinge area", "hinge damage"],
        "lid":            ["lid", "cover", "top lid", "top cover", "lid area"],
        "corner":         ["corner", "edge", "side edge", "laptop corner", "one corner"],
        "port":           ["port", "usb", "connector", "charging port", "hdmi"],
        "base":           ["base", "bottom", "chassis", "underside"],
        "body":           ["body", "casing", "case", "cover", "outer body", "body only"],
    },
    "package": {
        "box":            ["box", "delivery box", "cardboard box", "parcel", "outer box", "box condition", "box crushed", "wet box"],
        "package_corner": ["corner", "edge", "flap", "corner dab gaya", "package corner", "box corner"],
        "package_side":   ["side", "face", "panel", "surface", "package surface", "seal side", "wet box", "delivery box"],
        "seal":           ["seal", "tape", "closed", "opened", "seal broken", "seal torn", "seal area", "package seal"],
        "label":          ["label", "sticker", "barcode", "tag", "shipping label"],
        "contents":       ["content", "contents", "inside", "inner", "item", "product", "interior", "andar ka item", "product inside", "is missing", "are missing", "something inside"],
        "item":           ["item", "product", "unit", "inside item", "inner item", "is broken", "broken item"],
    },
}

CLAIM_TEMPLATES = [
    ("screen", {"issue": "crack", "part": "screen"}),
    ("cracked screen", {"issue": "crack", "part": "screen"}),
    ("display crack", {"issue": "crack", "part": "screen"}),
    ("broken screen", {"issue": "broken_part", "part": "screen"}),
    ("broken hinge", {"issue": "broken_part", "part": "hinge"}),
    ("hinge broken", {"issue": "broken_part", "part": "hinge"}),
    ("broken key", {"issue": "broken_part", "part": "keyboard"}),
    ("missing key", {"issue": "missing_part", "part": "keyboard"}),
    ("crack windshield", {"issue": "crack", "part": "windshield"}),
    ("broken windshield", {"issue": "glass_shatter", "part": "windshield"}),
    ("crack mirror", {"issue": "crack", "part": "side_mirror"}),
    ("broken mirror", {"issue": "broken_part", "part": "side_mirror"}),
    ("dent door", {"issue": "dent", "part": "door"}),
    ("dent bumper", {"issue": "dent", "part": "front_bumper"}),
    ("scratched bumper", {"issue": "scratch", "part": "front_bumper"}),
    ("scratched door", {"issue": "scratch", "part": "door"}),
    ("torn seal", {"issue": "torn_packaging", "part": "seal"}),
    ("torn package", {"issue": "torn_packaging", "part": "package_side"}),
    ("crushed box", {"issue": "crushed_packaging", "part": "box"}),
    ("dented box", {"issue": "crushed_packaging", "part": "box"}),
    ("water damage", {"issue": "water_damage", "part": "contents"}),
    ("stain label", {"issue": "stain", "part": "label"}),
    ("missing item", {"issue": "missing_part", "part": "item"}),
    ("missing part", {"issue": "missing_part", "part": "unknown"}),
    ("shattered glass", {"issue": "glass_shatter", "part": "windshield"}),
    ("broken headlight", {"issue": "broken_part", "part": "headlight"}),
    ("crack taillight", {"issue": "crack", "part": "taillight"}),
    ("dent hood", {"issue": "dent", "part": "hood"}),
    ("scratch hood", {"issue": "scratch", "part": "hood"}),
]
